### ISSUE TITLE
[Feature] videoAdTag implementation

### ISSUE THREAD

**Issue by bobaaaaa** [spring-media/rbbt-WeltContentApiClient#43]
Hier das Business-Regelwerk:

> Also Video soll momentan immer nur die oberste Section bekommen, also zB sport_video, wirtschaft_video etc.
> Bundesliga brauchen wir zzt. keine Sonderregeln

**Comment by thisismana** [comment]
können sie doch im CMCF so einstellen? warum sollen wir das ausprogrammieren?
