### ISSUE TITLE
[API] ApiSearchResponse misleading docs

### ISSUE THREAD

**Issue by bobaaaaa** [spring-media/rbbt-WeltContentApiClient#78]
```scala
/**
  * This class wraps search results from our API. Official documentation at https://content-api.up.welt.de
  *
  * @param page     current result page
  * @param pageSize result page size
  * @param pages    total number of pages available
  * @param total    total number of items that match the search
  * @param results  search result of type [[ApiContent]]
  *
  * @since 0.8
  */
```

All `Int` values starting at `0`?

**Comment by thisismana** [comment]
wollte nicht die content-api-doku kopieren, weil die sonst auseinanderlaufen, falls sich das Verhalten ändert. Alle Werte starten bei `1`.

**Comment by bobaaaaa** [comment]
Steht da aber nicht: https://content-api.up.welt.de/#_fields

Ich hab mich gefragt wie ein Response mit `Empty/Nil` Results aussieht?!

```json
{
  "page": 1,
  "pageSize": 1,
  "pages": 1,
  "total": 0,
  "results": []
}
```

**Comment by thisismana** [comment]
Yep. Fast richtig: https://doug-ecs-production.up.welt.de/_search?type=ooh

    {
      "response": {
        "page": 1,
        "pageSize": 30,
        "pages": 0,
        "total": 0,
        "took": 2,
        "nextPage": "https://doug-ecs-production.internal.welt.de:443/_search?type=ooh&page=2",
        "status": "ok",
        "results": []
      }
    }
