### ISSUE TITLE
@deprecated WCAC CurationService + PapyrusRepository

### ISSUE THREAD

**Issue by harryurban** [spring-media/rbbt-WeltContentApiClient#94]
**What**
CurationService and PapyrusRepository + Curated Models are moved from WCAC to Digger == `@deprecated`

**Why**
- Digger is only consumer for this
- Faster releases for Digger for curation
- Reduce WCAC Releases
- no service config needed in Apps that use WCAC

**Comment by bobaaaaa** [comment]
👍 +1
